---
title: "Stat 585 - R packages"
author: "Heike Hofmann"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

## Outline

- Another way of setting up a package

- data in packages

<br>
<br>
<br>

Resource: [usethis](https://usethis.r-lib.org/) by Hadley Wickham and Jenny Bryan

---
class: inverse
## Your Turn

`usethis` is a package to help with organizing your workflow in packages and non-package projects

Go through the [README](https://usethis.r-lib.org/) site of `usethis` and try the commands out to create a new package

Use `usethis` functionality to set up a README.Rmd file and a NEWS.md file.

---
class: inverse
## Your Turn

The `usethis` package allows you to directly connect a project to git and github

1. Check with `use_git_config()` that your user name and email are correct for qorking with github

2. Use `edit_git_config` is they are not correct and fix the information in the file

3. Then use `use_github()` - most likely this will result in an error, unless you have set up a token. Follow the instructions, restart R and try again. 

4. Go to your github page and check whether the new repo is there ... 

---

## Data in a package

- Data frames must be stored in the `data` folder using the command `save`. 

- Data documentation: http://r-pkgs.had.co.nz/data.html#documenting-data

```
#' Prices of 50,000 round cut diamonds.
#'
#' A dataset containing the prices and other attributes of almost 54,000
#' diamonds.
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{price}{price, in US dollars}
#'   \item{carat}{weight of the diamond, in carats}
#'   ...
#' }
#' @source \url{http://www.diamondse.info/}
"diamonds"
```


